import { getDataAsync } from "../api/getDataAsync";

export const roleTables = [
  {
    profession: "Test",
    tables: [
      "arrival-invoices",
      "bills-components",
      "bills-for-pay",
      "components_placement_type",
      "component_placements",
      "components",
      "current-task-states",
      "current-tasks",
      "current-tasks-components",
      "departments",
      "employee-departments",
      "employees",
      "employees_professions",
      "employees-vacations",
      "inventarization",
      "invoices-components",
      "license",
      "license_types",
      "order-request-components",
      "order-requests",
      "organization-types",
      "organizations",
      "pcb-order-states",
      "pcb-orders",
      "pcbs",
      "pcbs-components",
      "peoples",
      "professions",
      "server-arrivals",
      "server-writeoff",
      "shipment-package",
      "shipment-package-states",
      "shipment-trips",
      "shipments",
      "shipment-stands",
      "stand-packages",
      "stand-tasks",
      "stand-tasks-components",
      "stands",
      "stands-types",
      "students",
      "supplier-components",
      "suppliers",
      "user",
      "writeoff",
      "writeoff-reasons",
    ],
  },
  {
    profession: "Директор",
    tables: [
      "arrival-invoices",
      "bills-components",
      "bills-for-pay",
      "components_placement_type",
      "component_placements",
      "components",
      "current-task-states",
      "current-tasks",
      "current-tasks-components",
      "departments",
      "employee-departments",
      "employees",
      "employees_professions",
      "employees-vacations",
      "inventarization",
      "invoices-components",
      "license",
      "license_types",
      "order-request-components",
      "order-requests",
      "organization-types",
      "organizations",
      "pcb-order-states",
      "pcb-orders",
      "pcbs",
      "pcbs-components",
      "peoples",
      "professions",
      "server-arrivals",
      "server-writeoff",
      "shipment-package",
      "shipment-package-states",
      "shipment-trips",
      "shipments",
      "shipment-stands",
      "stand-packages",
      "stand-tasks",
      "stand-tasks-components",
      "stands",
      "stands-types",
      "students",
      "supplier-components",
      "suppliers",
      "user",
      "writeoff",
      "writeoff-reasons",
    ],
  },
  {
    profession: "Снабженец",
    tables: ["employees", "organizations", "user", "license_types"],
  },
  {
    profession: "Бухгалтер",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Заведущий производством",
    tables: ["employees", "organizations", "user", "license_types"],
  },
  {
    profession: "Программист",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Дизайнер",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Конструктор",
    tables: ["warehouse_components"],
  },
  {
    profession: "Инженер",
    tables: ["pcb_orders", "order_requests"],
  },
  {
    profession: "Монтажник",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Слесарь",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Инженер-универсал",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Токарь",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Фрезеровщик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Сварщик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Столяр",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Технолог ПП",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Покрасчик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Test",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
];
