import { getDataAsync } from "../api/getDataAsync";

export const roleTables = [
  {
    profession: "Test",
    tables: [
      "arrival_invoices",
      "bills_components",
      "bills_for_pay",
      "component_placement_types",
      "component_placements",
      "components",
      "current_task_states",
      "current_tasks",
      "current_tasks_components",
      "departments",
      "employee_departments",
      "employees",
      "employees_professions",
      "employees_vacations",
      "inventarization",
      "license",
      "license_types",
      "order_requests_components",
      "order_requests",
      "organization_types",
      "organizations",
      "pcb_order_states",
      "pcb_orders",
      "pcbs",
      "pcbs_components",
      "peoples",
      "professions",
      "server_arrivals",
      "server_writeoff",
      "shipment_package",
      "shipment_package_states",
      "shipment_trips",
      "shipments",
      "shipments_stands",
      "stand_packages",
      "stand_tasks",
      "stand_tasks_components",
      "stands",
      "stand_types",
      "supplier_components",
      "suppliers",
      "user",
      "writeoff",
      "writeoff_reasons",
    ],
  },
  {
    profession: "Директор",
    tables: [
      "arrival_invoices",
      "bills_components",
      "bills_for_pay",
      "component_placement_types",
      "component_placements",
      "components",
      "current_task_states",
      "current_tasks",
      "current_tasks_components",
      "departments",
      "employee_departments",
      "employees",
      "employees_professions",
      "employees_vacations",
      "inventarization",
      "invoices_components",
      "license",
      "license_types",
      "order_requests_components",
      "order_requests",
      "organization_types",
      "organizations",
      "pcb_order_states",
      "pcb_orders",
      "pcbs",
      "pcbs_components",
      "peoples",
      "professions",
      "server_arrivals",
      "server_writeoff",
      "shipment_package",
      "shipment_package_states",
      "shipment_trips",
      "shipments",
      "shipments_stands",
      "stand_packages",
      "stand_tasks",
      "stand_tasks_components",
      "stands",
      "stand_types",
      "supplier_components",
      "suppliers",
      "user",
      "writeoff",
      "writeoff_reasons",
    ],
  },
  {
    profession: "Снабженец",
    tables: [
      "employees",
      "organizations",
      "user",
      "license_types",
      "components",
      "current_tasks",
    ],
  },
  {
    profession: "Бухгалтер",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Заведущий производством",
    tables: ["employees", "organizations", "user", "license_types"],
  },
  {
    profession: "Программист",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Дизайнер",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Конструктор",
    tables: ["warehouse_components"],
  },
  {
    profession: "Инженер",
    tables: ["pcb_orders", "order_requests"],
  },
  {
    profession: "Монтажник",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Слесарь",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Инженер-универсал",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Токарь",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Фрезеровщик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Сварщик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Столяр",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Технолог ПП",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Покрасчик",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
  {
    profession: "Test",
    tables: ["employees", "organizations", "user", "license_types", "peoples"],
  },
];
