import { getDataAsync } from "../api/getDataAsync";

export const roleTables = [
  {
    profession: "Test",
    tables: [
      "components",
      "components_arrival_invoice",
      "components_invoice",
      "countries",
      "current_tasks",
      "departments",
      "employee_departments",
      "employee_states",
      "employee_tasks",
      "employees",
      "invoices_arrival",
      "license",
      "license_types",
      "locations",
      "order_request_components",
      "order_requests",
      "order_types",
      "organization_types",
      "organizations",
      "payment_invoice",
      "pcb_order_states",
      "pcb_orders",
      "pcb_warehouse_components",
      "pcbs",
      "peoples",
      "professions",
      "region",
      "sending_boxes",
      "shipment_package",
      "shipment_package_states",
      "shipment_states",
      "shipment_trips",
      "shipments",
      "stand_assemblies",
      "stand_categories",
      "stand_courses",
      "stand_packages",
      "stands",
      "stands_types",
      "students",
      "supplier_components",
      "suppliers",
      "task_types",
      "user",
      "warehouse_components",
    ],
  },
  {
    profession: "Администратор",
    tables: ["employees", "organizations", "user", "license_types"],
  },
  {
    profession: "Директор",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Секретарь",
    tables: ["employees", "organizations"],
  },
  {
    profession: "Снабженец",
    tables: ["warehouse_components"],
  },
  {
    profession: "Инженер",
    tables: ["pcb_orders", "order_requests"],
  },
  {
    profession: "IT-специалист",
    tables: ["employees", "organizations", "user", "license_types"],
  },
];
