export const sectionRules: Record<
  string,
  Record<
    string,
    { required?: boolean; type?: "number" | "string" | "date" | "boolean" }
  >
> = {
  components: {
    parentId: { required: false, type: "number" },
    title: { required: true, type: "string" },
    photo: { required: false, type: "string" },
    width: { required: false, type: "number" },
    height: { required: false, type: "number" },
    thickness: { required: false, type: "number" },
    weight: { required: false, type: "number" },
    material: { required: false, type: "string" },
    receiptDate: { required: false, type: "date" },
    drawingReference: { required: false, type: "string" },
    placementId: { required: false, type: "number" },
  },
  stand_tasks: {
    parentId: { required: false, type: "number" },
    order: { required: true, type: "number" },
    componentOutCount: { required: false, type: "number" },
    title: { required: true, type: "string" },
    photo: { required: false, type: "string" },
    manufactureTime: { required: true, type: "number" },
    professionId: { required: true, type: "number" },
    componentId: { required: false, type: "number" },
  },
  arrival_invoices: {
    date: { required: true, type: "date" },
    numberInvoice: { required: true, type: "string" },
    scanPhoto: { required: false, type: "string" },
    dateTimeToWarehouse: { required: false, type: "date" },
    price: { required: true, type: "number" },
    vat: { required: true, type: "boolean" },
    supplierId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
  },
  departments: {
    title: { required: true, type: "string" },
  },
  organization_types: {
    title: { required: true, type: "string" },
    icon: { required: false, type: "string" },
  },
  bills_for_pay: {
    date: { required: true, type: "date" },
    numberBill: { required: true, type: "string" },
    scanPhoto: { required: false, type: "string" },
    expectedSupplyDate: { required: false, type: "date" },
    totalAmount: { required: true, type: "number" },
    vat: { required: true, type: "boolean" },
    link: { required: false, type: "string" },
    supplierId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
  },
  component_placements: {
    building: { required: false, type: "string" },
    room: { required: false, type: "string" },
    placementTypeId: { required: true, type: "number" },
  },
  employees: {
    dismissalDate: { required: false, type: "date" },
    peoples: { required: false, type: "string" },
    peopleId: { required: false, type: "number" },
  },
  invetarization: {
    inventarizationDate: { required: true, type: "date" },
    componentCount: { required: true, type: "number" },
    inventarizationQuality: { required: false, type: "number" },
    componentId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
  },
  invoices_components: {
    componentCount: { required: true, type: "number" },
    componentId: { required: true, type: "number" },
    arrivalInvoiceId: { required: true, type: "number" },
  },
  license: {
    licenseTypeId: { required: false, type: "number" },
    licenseCode: { required: true, type: "string" },
    start: { required: false, type: "date" },
    end: { required: false, type: "date" },
    places: { required: false, type: "number" },
    timeout: { required: false, type: "string" },
    comment: { required: false, type: "string" },
    standId: { required: true, type: "number" },
  },
  license_types: {
    title: { required: true, type: "string" },
  },
  order_requests: {
    title: { required: true, type: "string" },
    requestDatetime: { required: true, type: "date" },
    executionDatetime: { required: false, type: "date" },
    comment: { required: false, type: "string" },
    factoryId: { required: true, type: "number" },
    standId: { required: true, type: "number" },
    employeeCreatorId: { required: true, type: "number" },
  },
  order_requests_components: {
    componentCount: { required: true, type: "number" },
    link: { required: false, type: "string" },
    comment: { required: false, type: "string" },
    orderRequestId: { required: true, type: "number" },
    componentId: { required: true, type: "number" },
    supplierId: { required: true, type: "number" },
  },
  organization_types: {
    title: { required: true, type: "string" },
    icon: { required: false, type: "string" },
  },
  organizations: {
    parentId: { required: false, type: "number" },
    fullName: { required: true, type: "string" },
    shortName: { required: true, type: "string" },
    lawAddress: { required: true, type: "string" },
    factAddress: { required: true, type: "string" },
    postAddress: { required: true, type: "string" },
    inn: { required: true, type: "string" },
    kpp: { required: true, type: "string" },
    orgn: { required: true, type: "string" },
    orgnDate: { required: true, type: "date" },
    phone: { required: true, type: "string" },
    email: { required: true, type: "string" },
    digitalDocs: { required: true, type: "boolean" },
    rating: { required: true, type: "number" },
    comment: { required: false, type: "string" },
    organizationTypeId: { required: true, type: "number" },
    contactPeopleId: { required: true, type: "number" },
  },
  pcb_orders: {
    orderDate: { required: true, type: "date" },
    billNumber: { required: true, type: "string" },
    count: { required: true, type: "number" },
    width: { required: true, type: "number" },
    height: { required: true, type: "number" },
    thickness: { required: true, type: "number" },
    article: { required: true, type: "string" },
    price: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
    pcbManufacturerId: { required: true, type: "number" },
    employeeId: { required: true, type: "number" },
    pcbOrderStatusId: { required: true, type: "number" },
  },
  pcbs: {
    parentId: { required: false, type: "number" },
    title: { required: true, type: "string" },
    standId: { required: true, type: "number" },
  },
  pcbs_components: {
    componentCount: { required: true, type: "number" },
    pcbId: { required: true, type: "number" },
    componentId: { required: true, type: "number" },
  },
  peoples: {
    email: { required: false, type: "string" },
    phone: { required: true, type: "string" },
    firstName: { required: true, type: "string" },
    lastName: { required: true, type: "string" },
    middleName: { required: false, type: "string" },
    comment: { required: false, type: "string" },
    birthDate: { required: false, type: "date" },
  },
  professions: {
    title: { required: true, type: "string" },
  },
  server_arrivals: {
    dateTime: { required: true, type: "date" },
    componentCount: { required: true, type: "number" },
    componentId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
    currentTaskId: { required: true, type: "number" },
  },
  server_writeoff: {
    dateTime: { required: true, type: "date" },
    componentCount: { required: true, type: "number" },
    componentId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
    currentTaskId: { required: true, type: "number" },
  },
  shipment_package: {
    photo: { required: false, type: "string" },
    weight: { required: true, type: "number" },
    width: { required: true, type: "number" },
    height: { required: true, type: "number" },
    stateId: { required: true, type: "number" },
    shipmentId: { required: true, type: "number" },
  },
  shipment_trips: {
    tripStartDate: { required: true, type: "date" },
    tripEndDate: { required: true, type: "date" },
    shipmentId: { required: true, type: "number" },
    employeeId: { required: true, type: "number" },
  },
  shipments: {
    price: { required: true, type: "number" },
    addedDate: { required: true, type: "date" },
    shipmentDate: { required: true, type: "date" },
    arrivalDate: { required: false, type: "date" },
    specificationImage: { required: true, type: "string" },
    comment: { required: false, type: "string" },
    licenseId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
    transporterId: { required: true, type: "number" },
    clientId: { required: true, type: "number" },
    standId: { required: true, type: "number" },
  },
  stand_tasks_components: {
    componentCount: { required: false, type: "number" },
    standTaskId: { required: true, type: "number" },
    componentId: { required: false, type: "number" },
  },
  stands: {
    parentId: { required: false, type: "number" },
    title: { required: true, type: "string" },
    image: { required: false, type: "string" },
    width: { required: false, type: "number" },
    height: { required: false, type: "number" },
    thickness: { required: false, type: "number" },
    weightNetto: { required: false, type: "number" },
    weightBrutto: { required: false, type: "number" },
    link: { required: false, type: "string" },
    vendorCode: { required: true, type: "string" },
    manufactureTime: { required: false, type: "number" },
    comment: { required: false, type: "string" },
    standTypeId: { required: true, type: "number" },
    employeeId: { required: true, type: "number" },
  },
  user: {
    userName: { required: true, type: "string" },
    password: { required: true, type: "string" },
    passwordSalt: { required: false, type: "string" },
    firstName: { required: true, type: "string" },
    lastName: { required: true, type: "string" },
    middleName: { required: false, type: "string" },
    comment: { required: false, type: "string" },
    birthDate: { required: false, type: "date" },
  },
  writeoff: {
    datetime: { required: true, type: "date" },
    count: { required: true, type: "number" },
    comment: { required: false, type: "string" },
    componentId: { required: true, type: "number" },
    factoryId: { required: true, type: "number" },
    writeoffReasonId: { required: true, type: "number" },
  },
};
