export enum tablesEnum {
  employees = "employees",
  shipments = "shipments",
  order_requests = "order_requests",
  organizations = "organizations",
  stands = "stands",
  stands_categories = "stands_categories",
  stand_tasks = "stand_tasks",
  pcbs_categories = "pcbs_categories",
  pcbs = "pcbs",
  components_categories = "components_categories",
  components = "components",
  departments = "departments",
  stands_types = "stands_types",
  stand_tasks_components = "stand_tasks_components",
  organization_types = "organization_types",
  arrival_invoices = "arrival_invoices",
  invoices_components = "invoices_components",
  bills_for_pay = "bills_for_pay",
  bills_components = "bills_components",
  license = "license",
  license_types = "license_types",
}
