export const NODE_TYPE_TO_TABLE = {
  stands: "stands",
  stand_tasks: "stand_tasks",
  current_tasks: "current_tasks",
  employees: "employees",
  departments: "departments",
  organizations: "organizations",
  organization_types: "organization_types",
  components: "components",
  pcbs: "pcbs",
  pcb_orders: "pcb_orders",
  bills_components: "bills_components",
  bills_for_pay: "bills_for_pay",
  arrival_invoices: "arrival_invoices",
  invoices_components: "invoices_components",
  inventarization: "inventarization",
}; 