export const NODE_TYPE_TO_TABLE = {
  stands: "stands",
  stand_tasks: "stand_tasks",
  stand_tasks_components: "stand_tasks_components",
  current_tasks: "current_tasks",
  license: "license",
  license_types: "license_types",
  employees: "employees",
  departments: "departments",
  organizations: "organizations",
  organization_types: "organization_types",
  components: "components",
  pcbs: "pcbs",
  pcb_orders: "pcb_orders",
  bills_components: "bills_components",
  bills_for_pay: "bills_for_pay",
  arrival_invoices: "arrival_invoices",
  invoices_components: "invoices_components",
  inventarization: "inventarization",
  shipments: "shipments",
  shipment_package: "shipment_package",
  components_categories: "components_categories",
  components_subcategories: "components_subcategories",
  pcbs_categories: "pcbs_categories",
  pcbs_subcategories: "pcbs_subcategories",
}; 